create database if not exists hallownet;
use hallownet;


create table usuario(
idUsuario int primary key auto_increment,
nome varchar(60),
username varchar(15) unique key,
email varchar(40) unique key,
senha varchar(80)
)auto_increment=100;

insert into	usuario (nome, username, email, senha)
	values ('Marilia Toscano', 'Mar', 'marilia.t.araujo@gmail.com', '123');

create table conquistas(
id int primary key auto_increment,
nome varchar(45),
imagem varchar(800),
descricao varchar(800)
);


create table usuario_conquistas(
fkusuario int,
fkconquista int,
dataHorario datetime,
status boolean default false,
primary key (fkusuario,fkconquista),
foreign key (fkusuario) references usuario(idUsuario),
foreign key (fkconquista) references conquistas(id)
);

select * from conquistas;
insert into conquistas(nome, imagem, descricao) 
	value('Afortunado', '<img src="./assets/conquistas/Achievement_Charmed.png">', 'Adquira seu primeiro Amuleto'),
		('Encantado', '<img src="./assets/conquistas/Achievement_Enchanted.png">', 'Adquira metade dos Amuletos de Hallownest.'),
        ('Abençoado', '<img src="./assets/conquistas/Achievement_Blessed.png">', 'Adquira todos os Amuletos e receba a bênção de Salubra.'),
        ('Protegido', '<img src="./assets/conquistas/Achievement_Protected.png">','Adquira 4 Fragmentos de Máscara.'),
        ('Mascarado', '<img src="./assets/conquistas/Achievement_Masked.png">','Adquira todos os Fragmentos de Máscara.'),
        ('Cheio de Alma', '<img src="./assets/conquistas/Achievement_Soulful.png">','Adquira 3 dos Fragmentos de Receptáculo.'),
        ('Alma do mundo', '<img src="./assets/conquistas/Achievement_Worldsoul.png">','Adquira todos os Fragmentos de Receptáculo.'),
        ('Falsidade', '<img src="./assets/conquistas/Achievement_Falsehood.png">','Derrote o False Knight.'),
        ('Força', '<img src="./assets/conquistas/Achievement_Strength.png">','Derrote o Failed Champion.'),
        ('Teste de Resolução','<img src="./assets/conquistas/Achievement_Test_of_Resolve.png">','Derrote Hornet em Greenpath'),
        ('Prova de Resolução','<img src="./assets/conquistas/Achievement_Proof_of_Resolve.png">',"Derrote Hornet em Kigdom's Edge."),
        ('Iluminação','<img src="./assets/conquistas/Achievement_Illumination.png">','Derrote o Soul Master.'),
        ('Mortalidade','<img src="./assets/conquistas/Achievement_Mortality.png">','Derrote o Soul Tyrant.'),
        ('Libertação','<img src="./assets/conquistas/Achievement_Release.png">','Derrote o Broken Vessel.'),
        ('Paz','<img src="./assets/conquistas/Achievement_Peace.png">','Derrote o Lost Kin.'),
        ('Honra','<img src="./assets/conquistas/Achievement_Honour.png">','Derrote o Dung Defender.'),
        ('Respeito','<img src="./assets/conquistas/Achievement_Respect.png">','Derrote os Mantis Lords.'),
        ('Obssessão','<img src="./assets/conquistas/Achievement_Obsession.png">','Derrote o Collector.'),
        ('Execução','<img src="./assets/conquistas/Achievement_Execution.png">','Derrote o Traitor Lord.'),
        ('Rivalidade','<img src="./assets/conquistas/Achievement_Rivalry.png">','Derrote o Zote no Coliseu dos Tolos.'),
        ('Sintonia','<img src="./assets/conquistas/Achievement_Attunement.png">','Colete 600 Essências.'),
        ('Despertar','<img src="./assets/conquistas/Achievement_Awakening.png">','Colete 1800 Essências e desperte o Ferrão dos Sonhos.'),
        ('Ascenção','<img src="./assets/conquistas/Achievement_Ascension.png">','Colete 2400 Essências e ouça as palavras finais da Vidente.'),
        ('Amigo das Larvas','<img src="./assets/conquistas/Achievement_Grubfriend.png">','Resgate metade das larvas prisioneiras.'),
        ('Metamorfose','<img src="./assets/conquistas/Achievement_Metamorphosis.png">','Resgate todas as larvas prisioneiras.'),
        ('Conexão','<img src="./assets/conquistas/Achievement_Connection.png">','Abra metade das Estações de Besouro de Hallownest.'),
        ('Esperança','<img src="./assets/conquistas/Achievement_Hope.png">','Abra todas as Estações de Besouro de Hallownest e descubra o Ninho dos Besouros.'),
        ('Negligência','<img src="./assets/conquistas/Achievement_Neglect.png">','Deixe Zote morrer.'),
        ('Testemunha','<img src="./assets/conquistas/Achievement_Witness.png">','Passe um momento final com Quirrel.'),
        ('Pureza','<img src="./assets/conquistas/Achievement_Purity.png">','Mate o Forjador de Ferrões com o Ferrão Puro.'),
        ('Casal Feliz','<img src="./assets/conquistas/Achievement_Happy_Couple.png">','Permita que o Forjador de Ferrões encontre uma nova vocação.'),
        ('Consolação','<img src="./assets/conquistas/Achievement_Solace.png">','Traga a paz para a Grey Mourner.'),
        ('Vazio','<img src="./assets/conquistas/Achievement_Void.png">','Relembre o passado e una o Abismo.'),
        ('Professora','<img src="./assets/conquistas/Achievement_Teacher.png">','Destrua Monomon a Professora.'),
        ('Observador','<img src="./assets/conquistas/Achievement_Watcher.png">','Destrua Lurien o Observador.'),
        ('Besta','<img src="./assets/conquistas/Achievement_Beast.png">','Destrua Herrah a Besta.'),
        ('Cartógrafo','<img src="./assets/conquistas/Achievement_Cartographer.png">','Adquira um mapa de cada área.'),
        ('Conclusão','<img src="./assets/conquistas/Achievement_Completion.png">','Consiga 100% de conclusão e termine o jogo.'),
        ('Conclusão Pura','<img src="./assets/conquistas/Achievement_Pure_Completion.png">','Conquiste 112% de conclusão e termine o jogo.'),
        ('Finallização Rápida','<img src="./assets/conquistas/Achievement_Speed_Completion.png">','Consiga 100% de conclusão e termine o jogo em menos de 20 horas.'),
        ('Caçador Habilidoso','<img src="./assets/conquistas/Achievement_Keen_Hunter.png">','Registre todas as criaturas de Hallownest no Diário do Caçador.'),
        ('Verdadeiro Caçador','<img src="./assets/conquistas/Achievement_True_Hunter.png">','Receba a Marca do Caçador.'),
        ('Alma de Aço','<img src="./assets/conquistas/Achievement_Steel_Soul.png">','Finalize o jogo no modo Alma de Aço.'),
        ('Coração de Aço','<img src="./assets/conquistas/Achievement_Steel_Heart.png">','Consiga 100% de conclusão do jogo no modo Alma de Aço.'),
        ('Speedrun 1','<img src="./assets/conquistas/Achievement_Speedrun_1.png">','Complete o jogo em menos de 10 horas.'),
        ('Speedrun 2','<img src="./assets/conquistas/Achievement_Speedrun_2.png">','Complete o Jogo em menos de 5 horas.'),
        ('Guerreiro','<img src="./assets/conquistas/Achievement_Warrior.png">','Complete a Provação do Guerreiro.'),
        ('Conquistador','<img src="./assets/conquistas/Achievement_Conqueror.png">','Complete a Provação do Conquistador.'),
        ('Tolo','<img src="./assets/conquistas/Achievement_Fool.png">','Complete a Provação do Tolo.'),
        ('O Cavaleiro Vazio','<img src="./assets/conquistas/Achievement_The_Hollow_Knight.png">','Derrote o Hollow Knight e torne-se o Receptáculo.'),
        ('Irmãos Selados','<img src="./assets/conquistas/Achievement_Sealed_Siblings.png">','Derrote o Hollow Knight com Hornet ao seu lado.'),
        ('Não Sonhe Mais','<img src="./assets/conquistas/Achievement_Dream_No_More.png">','Derrote a Radiance e consuma a luz.'),
        ('Passagem da Era','<img src="./assets/conquistas/Achievement_Passing_of_the_Age.png">','Ajude o Herald a seguir em frente.'),
        ('Memória','<img src="./assets/conquistas/Achievement_Memory.png">','Derrote o White Defender.'),
        ('Romance Sombrio','<img src="./assets/conquistas/Achievement_Dark_Romance.png">','Derrote o Grey Prince Zote.'),
        ('Grande Atuação','<img src="./assets/conquistas/Achievement_Grand_Performance.png">','Derrote o líder da Grimm Troupe.'),
        ('Ritual','<img src="./assets/conquistas/Achievement_Ritual.png">','Derrote o Nightmare King e complete o ritual.'),
        ('Banimento','<img src="./assets/conquistas/Achievement_Banishment.png">','Bana a Grimm Troupe de Hallownest.'),
        ('Irmandade','<img src="./assets/conquistas/Achievement_Brotherhood.png">','Complete o Panteão do Mestre.'),
        ('Inspiração','<img src="./assets/conquistas/Achievement_Inspiration.png">','Complete o Panteão do Pintor.'),
        ('Foco','<img src="./assets/conquistas/Achievement_Focus.png">','Complete o Panteão do Sábio.'),
        ('Alma e Sombra','<img src="./assets/conquistas/Achievement_Soul_&_Shade.png">','Complete o Panteão do Cavaleiro.'),
        ('Abrace o Vazio','<img src="./assets/conquistas/Achievement_Embrace_the_Void.png">','Ascenda no Panteão de Hallownest e tome o seu lugar no pico.');
        
        
        -- Inserção de conquistas para fkusuario = 100, fkconquista de 1 a 63
INSERT INTO usuario_conquistas (fkusuario, fkconquista, dataHorario, status) VALUES
(100, 1, '2022-01-24 21:05:00', true),
(100, 2, '2022-01-28 17:22:00', true),
(100, 3, '2022-02-10 19:50:00', true),
(100, 4, '2022-01-28 17:22:00', true),
(100, 5, '2022-02-10 17:04:00', true),
(100, 6, '2022-01-28 17:22:00', true),
(100, 7, '2022-01-28 17:22:00', true),
(100, 8, '2022-01-24 20:57:00', true),
(100, 9, '2022-01-28 17:22:00', true),
(100, 10, '2022-01-25 22:40:00', true),
(100, 11, '2022-01-28 17:22:00', true),
(100, 12, '2022-01-28 17:22:00', true),
(100, 13, '2022-03-02 13:04:00', true),
(100, 14, '2022-01-28 17:22:00', true),
(100, 15, '2022-01-28 17:22:00', true),
(100, 16, '2022-01-28 17:22:00', true),
(100, 17, '2022-01-26 17:33:00', true),
(100, 18, '2022-01-28 17:22:00', true),
(100, 19, '2022-01-28 17:22:00', true),
(100, 20, '2022-03-14 18:04:00', true),
(100, 21, '2022-01-28 17:22:00', true),
(100, 22, '2022-01-28 17:22:00', true),
(100, 23, '2022-03-02 12:27:00', true),
(100, 24, '2022-01-28 17:22:00', true),
(100, 25, '2022-01-28 17:30:00', true),
(100, 26, '2022-01-28 17:45:00', true),
(100, 27, '2022-02-07 10:09:00', true),
(100, 28, null, false),
(100, 29, '2022-02-10 16:32:00', true),
(100, 30, '2022-02-10 13:27:00', true),
(100, 31, '2022-01-28 19:00:00', true),
(100, 32, '2022-02-10 17:04:00', true),
(100, 33, '2022-02-12 01:08:00', true),
(100, 34, '2022-01-28 15:00:00', true),
(100, 35, '2022-01-28 18:30:00', true),
(100, 36, '2022-01-28 19:30:00', true),
(100, 37, '2022-01-28 16:45:00', true),
(100, 38, '2022-02-12 00:42:00', true),
(100, 39, null, false),
(100, 40, null, false),
(100, 41, '2022-04-20 17:04:00', true),
(100, 42, '2022-04-21 14:24:00', true),
(100, 43, null, false),
(100, 44, null, false),
(100, 45, null, false),
(100, 46, null, false),
(100, 47, '2022-01-28 08:15:00', true),
(100, 48, '2022-01-28 09:30:00', true),
(100, 49, '2022-04-18 21:16:00', true),
(100, 50, '2022-02-12 00:39:00', true),
(100, 51, '2022-03-06 18:54:00', true),
(100, 52, '2022-03-06 18:48:00', true),
(100, 53, '2022-03-06 18:50:00', true),
(100, 54, '2022-03-02 12:25:00', true),
(100, 55, '2022-04-19 19:09:00', true),
(100, 56, '2022-02-10 12:33:00', true),
(100, 57, '2022-03-14 17:40:00', true),
(100, 58, null, false),
(100, 59, '2022-04-24 20:00:00', true),
(100, 60, '2022-04-25 23:05:00', true),
(100, 61, null, false),
(100, 62, null, false),
(100, 63, null, false);

